use_frameworks!

target 'HTagView_Example' do
  pod 'HTagView', :path => '../'

  target 'HTagView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
  pod 'Nimble', '~> 5.0'
#  pod 'FBSnapshotTestCase'
#  pod 'Nimble-Snapshots'
  end
end
