use_frameworks!

target 'HTagView_Example' do
  pod 'HTagView', :path => '../'

  target 'HTagView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
